### ISSUE TITLE
Issues on sample deployment

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/sbgn-validation-service#4]
- [x] Update About page.
- [x] Errors and SBGNML download buttons don't work.
- [x] Let's change tooltip of SBGNML download button from "Download JSON file" to "Download SBGNML file".
- [x] In the 1st and 2nd samples, when "Fix Errors" is applied, all errors appear to be fixed, but some highlighted nodes are still visible in the image. I think we're unhighlighting fixed bugs, right?
- [x] Image settings are not applied when "Fix Errors" is applied.
- [x] Maybe we can keep "Fix Errors" button disabled, if map is valid.
- [x] Let's check again whether we apply layout correctly after "Fix Errors" operation. The layout looks very bad in the first sample, if that's really the case, maybe we can change the sample.
![image](https://github.com/iVis-at-Bilkent/sbgn-validation-service/assets/22586369/b3420f4c-cd5f-4218-ae2c-f93c632b79d7)
- [x] When errors are downloaded as JSON, there ia an unnecessary \n at the end of _text_ field:
"text": "If there are compartments defined, top-level glyphs must have a compartment reference\n"

- [x] After errors are fixed, when we download the results as JSON file, the format of text field changes with square brackets and multiple tabs at the end as follows (Let's make it same as after applying "Validate Map"):
    "text": [
      "If there are compartments defined, top-level glyphs must have a compartment reference\n\t\t\t"
    ], 

- [x] Let's disable SBGNML download button when no file is uploaded.
- [x] Let's use the name of the uploaded file while downloading the fixed version.

**Comment by YusufZiyaOzgul** [comment]
@hasanbalci can you test it ?
