### ISSUE TITLE
Error using outside Bilkent network

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/sbgn-validation-service#9]
If I don't use the VPN and try to load the first sample, I get the following error (from outside the campus):
![image](https://github.com/iVis-at-Bilkent/sbgn-validation-service/assets/3874988/b2a8dfec-c4fe-41bb-9e07-472fe8093b7d)

**Comment by YusufZiyaOzgul** [comment]
Now, it works outside Bilkent Network, without using VPN.
